export const reducercases = {
    SET_USER_INFO:"SET_USER_INFO",
    SET_NEW_USER_INFO:"SET_NEW_USER_INFO",
    SET_ALL_CONTACT_PAGE:"SET_ALL_CONTACT_PAGE",
    CHANGE_CURRENT_USER:"CHANGE_CURRENT_USER",
    SET_MESSAGES:"SET_MESSAGES",
    SET_SOCKET:"SET_SOCKET",
    ADD_MESSAGE:"ADD_MESSAGE",
}